server:
  port: 8003

spring:
  application:
    name: cloud-payment-service


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取自己的注册信息，默认为treu，单节点无所谓，集群必须设置为treu才能配合ibbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka #集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true
