server:
  port: 8012

spring:
  application:
    name: cloud-controller-charge
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.234.153:3306/biyesheji?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: w.19971214

#mybatis:
 # mapperLocations: classpath:mapper/*.xml
  #type-aliases-package: com.cloud.springcloud.entities


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取自己的注册信息，默认为treu，单节点无所谓，集群必须设置为treu才能配合ibbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka #集群版
  instance:
    instance-id: ChargeClien
    prefer-ip-address: true
