server:
  port: 7001


eureka:
  instance:
    hostname: 127.0.0.1 #eureka服务端的实例名称
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与ureka server交互的地址查询服务和注册服务都需要依赖这个地址192.168.5.199
      defaultZone: http://100.64.77.136:7002/eureka

